export const ResourceTypeEnum = {
  TEST_FUNCTIONAL: 'TEST_FUNCTIONAL',
  DEV_BE_SENIOR: 'DEV_BE_SENIOR',
  TEST_AUTOMATION: 'TEST_AUTOMATION',
  SPECIAL_DEVOPS: 'SPECIAL_DEVOPS',
  BA_REQ_ENGR: 'BA_REQ_ENGR',
  DEV_MOBILE_JUNIOR: 'DEV_MOBILE_JUNIOR',
  DEV_BE_JUNIOR: 'DEV_BE_JUNIOR',
  BA_JUNIOR: 'BA_JUNIOR',
  DEV_FE_JUNIOR: 'DEV_FE_JUNIOR',
  DEV_MOBILE_SENIOR: 'DEV_MOBILE_SENIOR',
  SPECIAL_ARCH: 'SPECIAL_ARCH',
  DEV_FE_SENIOR: 'DEV_FE_SENIOR',
  BA_SENIOR: 'BA_SENIOR',
  SPECIAL_PM: 'SPECIAL_PM',
  DEV_FULL_STACK_SENIOR: 'DEV_FULL_STACK_SENIOR',
  DEV_FULL_STACK_JUNIOR: 'DEV_FULL_STACK_JUNIOR'
}